name: mdedit
description: A cross-platform flutter Markdown editor
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.7.3
  get_it: ^7.6.0
  go_router: ^10.1.0
  flutter_acrylic: ^1.1.3
  flutter_localizations:
    sdk: flutter

  mdedit_api:
    path: ./mdedit_api
  mdedit_windows:
    path: ./mdedit_windows
  mdedit_linux:
    path: ./mdedit_linux
  mdedit_web:
    path: ./mdedit_web
  mdedit_macos:
    path: ./mdedit_macos

  macos_ui: ^2.0.0
  system_theme: ^2.3.1
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0