name: mdedit
description: A cross-platform flutter Markdown editor
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  adwaita:
    path: ../adwaita
  adwaita_icons: ^0.2.1

  cupertino_icons: ^1.0.2 

  file_picker: ^5.3.3
  flutter_markdown: ^0.6.17+1
  fluent_ui: ^4.7.3
  flutter_acrylic: ^1.1.3
  flutter_localizations:
    sdk: flutter

  
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0

  intl_utils: ^2.8.2
  intl: ^0.18.0

  macos_ui: ^2.0.0
  markdown: ^7.1.1
  
  split_view: ^3.2.1
  stacked: ^3.2.7
  system_theme: ^2.3.1
  
  window_manager: ^0.3.5

flutter_intl:
  enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


