name: mdedit
description: A cross-platform flutter Markdown editor
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  macos_ui: ^2.0.0

  adwaita: ^1.0.1
  adwaita_icons: ^0.2.1

  fluent_ui: ^4.7.2
  flutter_acrylic: ^1.1.3

  file_picker: ^5.3.3
  get_it: ^7.6.0
  go_router: ^10.0.0
  stacked: ^3.2.7

  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.2
  intl: ^0.18.0
  flutter_markdown: ^0.6.17+1
  split_view: ^3.2.1
  google_fonts: ^5.1.0
  markdown: ^7.1.1

flutter_intl:
  enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


