name: mdedit_api
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  get_it: ^7.6.0
  go_router: ^10.1.0

  file_picker: ^5.3.4
  flutter_localizations:
    sdk: flutter

  google_fonts: ^5.1.0

  intl_utils: ^2.8.2
  intl: ^0.18.0

  markdown: ^7.1.1

  window_manager: ^0.3.5

flutter_intl:
  enabled: true

flutter:
  generate: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

