name: mdedit_windows
description: Windows implementation of mdedit.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  mdedit_api:
    path: ../mdedit_api

  fluent_ui: ^4.7.3
  file_picker: ^5.3.4
  flutter_acrylic: ^1.1.3
  flutter_markdown: ^0.6.17+1
  get_it: ^7.6.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  markdown: ^7.1.1
  split_view: ^3.2.1
  stacked: ^3.2.7
  system_theme: ^2.3.1
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.3