name: mdedit
version: 0.1.0
summary: Markdown editor
description: Markdown editor
confinement: strict
base: core22
grade: stable
icon: snap/gui/app_icon.png

apps:
  mdedit:
    command: mdedit
    extensions: [gnome]

parts:
  mdedit:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart