name: mdedit
version: 0.1.0
summary: Super Cool App
description: Super Cool App that does everything!

confinement: strict
base: core18
grade: stable

slots:
  dbus-mdedit:
    interface: dbus
    bus: session
    name: org.cyanotic.md_edit

apps:
  mdedit:
    command: mdedit
    extensions: [flutter-stable]
    plugs:
      - network
    slots:
      - dbus-mdedit

parts:
  mdedit:
    source: .
    plugin: flutter
    flutter-revision: cc3ca9a916cb1da851a1f36432154a534787da99
    flutter-target: lib/main.dart
