name: mdedit
version: 0.0.1
summary: Markdown editor
description: Markdown editor
confinement: strict
base: core22
grade: stable
icon: snap/gui/app_icon.png

apps:
  mdedit:
    command: mdedit_linux
    extensions: [gnome]

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.13.2
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  mdedit:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cd mdedit_linux
      flutter doctor
      flutter clean
      flutter pub get
      flutter build linux --release
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
      find $CRAFT_PART_INSTALL -type f
      find /root/prime
      find /root/project