name: mdedit
version: 0.1.0
summary: Super Cool App
description: Super Cool App that does everything!

confinement: strict
base: core22
grade: stable

slots:
  dbus-mdedit:
    interface: dbus
    bus: session
    name: org.cyanotic.md_edit

apps:
  mdedit:
    command: mdedit
    extensions: [ gnome ]
    plugs:
      - network
    slots:
      - dbus-mdedit

parts:
  mdedit:
    source: .
    plugin: flutter
    flutter-channel: stable
    flutter-target: lib/main.dart
