name: mdedit_web
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  mdedit_api:
    path: ../mdedit_api

  flutter_markdown: ^0.6.17+1
  get_it: ^7.6.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  split_view: ^3.2.1
  stacked: ^3.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: mdedit
    platforms:
      web:
  uses-material-design: true
