name: Create binaries
run-name: Create binaries
on: [push]

jobs:
 build-linux:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.10.6'
         channel: 'stable'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter --version
     - run: flutter config --enable-linux-desktop
     - run: flutter pub get
     - run: flutter build linux --release
     - uses: actions/upload-artifact@v3
       with:
         name: linux
         path: build/linux/x64/release/bundle/*
 build-windows:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.10.6'
         channel: 'stable'
     - run: flutter config --enable-windows-desktop
     - run: flutter pub get
     - run: flutter build windows --release
     - uses: actions/upload-artifact@v3
       with:
         name: windows
         path: build//windows/runner/Release/*
 build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6'
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build macos --release
    - uses: actions/upload-artifact@v3
      with:
         name: macos
         path: build/macos/*
 build-web:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.10.6'
         channel: 'stable'
     - run: flutter pub get
     - run: flutter build web
     - uses: actions/upload-artifact@v3
       with:
         name: web
         path: build/web/*
