name: Create binaries
run-name: Create binaries
on:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    defaults:
      run:
        working-directory: mdedit_linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
      - name: Create snap app
        run: snapcraft --use-lxd
        working-directory: mdedit_linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: mdedit*.snap
  build-windows:
    defaults:
      run:
        working-directory: mdedit_windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
      - run: dart pub run intl_utils:generate
        working-directory: mdedit_api
      - run: flutter build windows --release
        working-directory: mdedit_windows
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/runner/Release/*
  build-macos:
    defaults:
      run:
        working-directory: mdedit_macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
          architecture: x64
      - run: dart pub run intl_utils:generate
        working-directory: mdedit_api
      - run: flutter build macos --release
        working-directory: mdedit_macos
      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/macos/Build/Products/Release/*.app
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
      - run: dart pub run intl_utils:generate
        working-directory: mdedit_api
      - run: flutter build web --release
        working-directory: mdedit_web
      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: mdedit_web/build/web/*
